# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'VBKitDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VBKit
pod 'AFNetworking'
pod 'SDWebImage'
pod 'FMDB/SQLCipher'
pod 'MJExtension'
pod 'MJRefresh'
pod 'CocoaLumberjack'
pod 'Reachability'
pod 'ZipArchive'
pod 'BFKit'
pod 'Masonry'
pod 'WSProgressHUD'

  target 'VBKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VBKitDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
